In [50]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [ ]:
# Loading Dataset
data = datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [ ]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=0.35)

In [ ]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(97, 4)
(53, 4)


In [ ]:
# Building the Model
model= Sequential()
model.add(Dense(16, activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(16, activation='softmax'))

In [ ]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [ ]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 3ms/step - loss: 2.6669 - accuracy: 0.0000e+00
Epoch 2/20
4/4 [==============================] - 0s 3ms/step - loss: 2.5830 - accuracy: 0.0000e+00
Epoch 3/20
4/4 [==============================] - 0s 2ms/step - loss: 2.5010 - accuracy: 0.0412
Epoch 4/20
4/4 [==============================] - 0s 2ms/step - loss: 2.4210 - accuracy: 0.1649
Epoch 5/20
4/4 [==============================] - 0s 2ms/step - loss: 2.3363 - accuracy: 0.3093
Epoch 6/20
4/4 [==============================] - 0s 2ms/step - loss: 2.2530 - accuracy: 0.3402
Epoch 7/20
4/4 [==============================] - 0s 2ms/step - loss: 2.1704 - accuracy: 0.3402
Epoch 8/20
4/4 [==============================] - 0s 3ms/step - loss: 2.0890 - accuracy: 0.3814
Epoch 9/20
4/4 [==============================] - 0s 3ms/step - loss: 2.0067 - accuracy: 0.5464
Epoch 10/20
4/4 [==============================] - 0s 3ms/step - loss: 1.9222 - accuracy: 0.6495
Epoch 11/20
4/4 [==============

In [ ]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 7ms/step - loss: 1.0114 - accuracy: 0.6604


[1.0113916397094727, 0.6603773832321167]

In [ ]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

1/1 [==============================] - 0s 51ms/step
[[5.53069152e-02 1.08045764e-01 6.96868658e-01 6.20934274e-03
  1.49788540e-02 6.51997048e-03 1.52220400e-02 4.76095651e-04
  8.85899353e-04 6.01422787e-03 3.92057784e-02 6.72488334e-03
  1.73844136e-02 1.25791365e-02 6.12671534e-03 7.45135685e-03]
 [7.97474831e-02 1.66533411e-01 6.17934823e-01 3.84330819e-03
  9.50813852e-03 5.83157223e-03 1.64274499e-02 3.42387357e-04
  5.98322367e-04 4.10858542e-03 5.48211075e-02 5.24269463e-03
  1.72796622e-02 8.16700980e-03 4.59975004e-03 5.01427054e-03]
 [1.26303822e-01 1.96647286e-01 4.26096410e-01 8.77576414e-03
  1.98280215e-02 1.35678984e-02 3.44059169e-02 1.86346308e-03
  2.28932314e-03 1.03145922e-02 7.69048333e-02 1.11939088e-02
  2.99133249e-02 1.67820565e-02 1.28456941e-02 1.22676156e-02]
 [3.33116561e-01 1.26520589e-01 9.27748159e-02 1.13577619e-02
  3.12554203e-02 2.42894217e-02 6.75835237e-02 1.95104256e-02
  6.66072359e-03 1.88746545e-02 1.19009994e-01 1.83039289e-02
  3.93159911e-0

In [ ]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[2 2 2 0 2 2 2 2 0 0]
[2 2 1 0 2 1 1 1 0 0]


In [ ]:
# Prediction Result
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
